[Fixes #350] Add more filters for pdn
geosolutions-it/nexus-geonode pull request #386
Opened 2021-07-29 10:52 UTC by meomancer

This fix https://github.com/geosolutions-it/nexus-geonode/issues/350

2021-07-29 17:49 UTC, ricardogsilva requested changes
Please take note of the inline comments I left.

The one about PostgREST API is a bug and the other one about the filters shall make stuff more readable and also more usable for the end user.

2021-07-29 17:49 UTC, ricardogsilva commented on src/nexus/utils.py
> +            result = len(response.json())
This method retrieves the number of existing records by inspecting the contents of the `Content-Range` HTTP header of the response. Because of this, it explicitly sets a `Range:0-0` as one of the request headers, which means that the PostgREST API will only return a single result (if it exists). It should never return the total number of results directly in the response - we don't want to risk the remote server returning millions of records in this JSON payload.

Additionally, the [docs] say that PostgREST API is supposed to return with HTTP status code of 206 (partial content), so I don't think we need to be checking for status 200 (ok).

With this in mind, it seems this proposed implementation does not work at all. Please refactor

[docs]: https://postgrest.org/en/stable/api.html#exact-count

2021-07-29 17:49 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +            active_filter: typing.Optional[bool] = None,
Please make the names of the params reflect the type of resource that they apply to. For example, if both news and alerts accept `start_date` and `end_date` filtering options, then please use `news_start_date`, `news_end_date`, `alerts_start_date` and `alerts_end_date` as filtering parameters.

This will make it easier to see which filtering options apply to which remote resource and it will also make the configuration more flexible for the end user - the proposed implementation does not allow e.g. setting a different start date for news and alerts.

This change shall have a big impact on the code below that does the parsing of params. Please adjust the whole PR with this in mind.

2021-07-30 06:15 UTC, meomancer commented on src/pdn/harvesters.py
> +            active_filter: typing.Optional[bool] = None,
updated @ricardogsilva

2021-07-30 06:16 UTC, meomancer commented on src/nexus/utils.py
> +            result = len(response.json())
i change it to not check json, but we still need to check 200 @ricardogsilva 
when it just return 1 item, it will return 200 (ok)
because i think it is not partial
you could check these url:
http://www.pacificdisaster.net/api/alert?daterecieved=gte.2014-05-12T12%3A02%3A05Z
http://www.pacificdisaster.net/api/document?publicationday=eq.23&publicationmonth=eq.7&publicationyear=eq.2018

![Selection_007](https://user-images.githubusercontent.com/4530905/127609322-354fd27a-d924-4cf1-b735-988fdaa80dfd.png)

2021-07-30 08:29 UTC, ricardogsilva commented
@meomancer 

You're right, the API does seem to sometimes send back a status of 200.

When issuing a request with these headers (which the browser does not automatically add btw):

```
Range-Unit: items
Range: 0-0
Prefer: count=exact
```

This tells PostgREST to give back a response with the `Content-Range` header, which contains the total number of records, while at the same time asking to only be returned a single record in the response body.

I have checked your example URLs and indeed it seems you are right that sometimes the response has a status of 200. This seems to happen when the result of the filters is a single record - I guess it makes sense, since we are asking for one record back and there is only one, so it is not really a partial content response.

The refactored change seems right now, thanks :)

2021-07-30 08:56 UTC, ricardogsilva requested changes
Getting there :smiley_cat: 

Please work on the changes requested inline

2021-07-30 08:56 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +            active_filter: typing.Optional[bool] = None,
`publication_day`, `publication_month`, `publication_year` and `active_filter` all need to also have the name of the remote resource that they apply to.

Looking at the code below it seems like all of the publication filters apply to documents and the active filter applies to projects. Make this explicit (_e.g._ `document_publication_day`) so that it is easier and more readable to configure the harvester on the django admin

2021-07-30 08:56 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +                total_resources[PdnResourceType.EXPERT]
In this case I don't mind it, but in the future please try to avoid making this kind of whitespace-only change unless it is fixing some pep8 violation, or if it is a commit dedicated to only do this type of cosmetic changes - I realize this was probably your IDE that made it automatically, but it ends up polluting the git history.

2021-07-30 08:56 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +        return params
IMO it would be better to put this business logic in four different methods, as in `_get_document_params()`, `_get_news_article_params()`, `_get_alert_params()`, etc.

Generally, when a function body is mostly composed of an `if..elif..else` block it is usually better to split it into smaller functions for each branch of the `if` and just do the conditional test outside, before calling the function - this has the added benefit of making the code require less indentation inside each function (multiple indentation makes code uglier, harder to read).

In this case this makes even more sense because you are already calling this method inside an `if` block (look below where this method is used).

2021-07-30 08:56 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +                f"/{PdnResourceType.ALERT.value}", params=self._get_params(PdnResourceType.ALERT))
According to my comment above, this would be more elegant:

```python
if self.harvest_alerts:
    result[PdnResourceType.ALERT] = self._api_client.get_total_records(
        f"/{PdnResourceType.ALERT.value}",
        params=self._get_alert_params()
    )
```

2021-07-30 08:56 UTC, ricardogsilva commented on src/nexus/utils.py
> +        if response.status_code == requests.codes.partial_content or response.status_code == requests.codes.ok:
Looking good now. I would even suggest a shorter alternative (since this is in a single line):

```suggestion
        if response.status_code in (requests.codes.partial_content, requests.codes.ok):
```

2021-08-05 03:58 UTC, meomancer commented on src/pdn/harvesters.py
> +            active_filter: typing.Optional[bool] = None,
updated @ricardogsilva

2021-08-05 03:58 UTC, meomancer commented on src/pdn/harvesters.py
> +                total_resources[PdnResourceType.EXPERT]
updated @ricardogsilva

2021-08-05 03:58 UTC, meomancer commented on src/pdn/harvesters.py
> +        return params
updated @ricardogsilva

2021-08-05 03:58 UTC, meomancer commented on src/pdn/harvesters.py
> +                f"/{PdnResourceType.ALERT.value}", params=self._get_params(PdnResourceType.ALERT))
updated @ricardogsilva

2021-08-05 03:58 UTC, meomancer commented on src/nexus/utils.py
> +        if response.status_code == requests.codes.partial_content or response.status_code == requests.codes.ok:
updated @ricardogsilva

2021-08-06 14:42 UTC, ricardogsilva requested changes
Almost ready. Please work on the inline comments and then request a review from either @giohappy or @afabiani  to cover for my absence.

Personally, I will be +1 if you change the current comments (and keep the rest the same).

2021-08-06 14:42 UTC, ricardogsilva commented on src/nexus/utils.py
> +            params: dict = dict
Using `dict` as a type annotation is not supported on Python < 3.9, we should use `typing.Dict` instead, since AFAIK GeoNode wants to support at least Python 3.8. 

Moreover, passing `dict` as the default value for params seems like a subtle bug. `dict` is a type that, when called, creates dictionaries. In other words:

```python
dict == {}
False

dict() == {}
True
```

Since dictionaries are mutable, they shouldn't be used as default values in Python functions, as that can lead to bugs. The usual way is to pass `None` as the default value and then check inside the function body if we got a dict sent in as an input. In this case, since `params` is passed straight to `self.http_session.get()`, you don't even need to check if it is `None` or not, since `requests` already does that.

```suggestion
            params: typing.Optional[typing.Dict] = None
```

2021-08-06 14:42 UTC, ricardogsilva commented on src/nexus/utils.py
> +            params: dict = dict
Same comment as above wrt using `dict` 

```suggestion
            params: typing.Optional[typing.Dict] = None
```

2021-08-06 14:42 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +                "project_active_filter", None),
`dict.get()` already returns `None` if no default is supplied, so please simplify this passage

```suggestion
            document_publication_day_filter=harvester.harvester_type_specific_configuration.get("document_publication_day_filter"),
            document_publication_month_filter=harvester.harvester_type_specific_configuration.get("document_publication_month_filter"),
            document_publication_year_filter=harvester.harvester_type_specific_configuration.get("document_publication_year_filter"),
            alerts_start_date_filter=harvester.harvester_type_specific_configuration.get("alerts_start_date_filter"),
            alerts_end_date_filter=harvester.harvester_type_specific_configuration.get("alerts_end_date_filter"),
            news_start_date_filter=harvester.harvester_type_specific_configuration.get("news_start_date_filter"),
            news_end_date_filter=harvester.harvester_type_specific_configuration.get("news_end_date_filter"),
            project_active_filter=harvester.harvester_type_specific_configuration.get("project_active_filter"),
```

2021-08-06 14:42 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +        return params
As per my previous comment about this function, now that you have made a function that deals with each branch of the `if..else` block, it seems there is no reason for this `_get_params()` method to exist anymore.

2021-08-06 14:42 UTC, ricardogsilva commented on src/pdn/harvesters.py
> +            )
This is how you'd replace `_get_params()` usage in this method. Please refactor accordingly

```python
        if self.harvest_alerts:
            result[PdnResourceType.ALERT] = self._api_client.get_total_records(f"/{PdnResourceType.ALERT.value}")
            result[PdnResourceType.ALERT] = self._api_client.get_total_records(
                f"/{PdnResourceType.ALERT.value}",
                params=self._get_alert_params()
            )
```

2021-08-06 14:42 UTC, ricardogsilva commented on src/pdn/harvesters.py
>          if should_list:
You can replace `_get_params()` with the specific function for each type here by doing something like this:

```python
        should_list, params_handler = {
            PdnResourceType.ALERT: (self.harvest_alerts, self._get_alert_params),
            PdnResourceType.DOCUMENT: (self.harvest_documents, self._get_document_params),
            PdnResourceType.EXPERT: (self.harvest_experts, self._get_expert_params),
            PdnResourceType.NEWS_ARTICLE: (self.harvest_news, self._get_news_article_params),
            PdnResourceType.PROJECT: (self.harvest_projects, self._get_project_params),
        }.get(resource_type, (False, None))
        result = []
        if should_list:
            raw_result = self._api_client.get_paginated_resources(
                f"/{resource_type.value}",
                offset,
                params=params_handler()
            )
```

2021-08-12 03:12 UTC, meomancer commented on src/nexus/utils.py
> +            params: dict = dict
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/nexus/utils.py
> +            params: dict = dict
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/pdn/harvesters.py
> +                "project_active_filter", None),
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/pdn/harvesters.py
> +        return params
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/pdn/harvesters.py
> +            )
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/pdn/harvesters.py
>          if should_list:
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/pdn/harvesters.py
>          if should_list:
updated @ricardogsilva

2021-08-12 03:12 UTC, meomancer commented on src/pdn/harvesters.py
> +            )
updated @ricardogsilva

2021-08-12 04:57 UTC, meomancer commented
could you review this @giohappy?

2021-08-25 07:53 UTC, giohappy commented
@meomancer what aboout start and end date filters for GeoNode? #350 should be split into two issues, one for GeoNode and one for PDN. I don't see the one for GeoNode thoufh.

2021-08-25 08:18 UTC, giohappy commented
ok, I see that it was created in GeoNode and I already merged the PR :)
I've updated the title of https://github.com/GeoNode/geonode/issues/7880 to make it clear that it's only for the GeoNode harvester.
Sorry but I'm recovering all my work from the holidays.

2021-08-25 08:19 UTC, giohappy approved these changes

2021-08-25 08:19 UTC, merged